OnlineOrderApp/urls.py
from django.conf.urls import url

from . import views, apis

urlpatterns = [
    url(r'^home', views.home),
    url(r'^process_payment/$', apis.payment,name='process-payment')
]

TealiciousOrdersProject/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from rest_framework.authtoken import views as rest_framework_views

from OnlineOrderApp import views, apis

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html')),
    url(r'^AboutUS.html/$', TemplateView.as_view(template_name='AboutUS.html')),

    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('OnlineOrderApp.urls')),
    # ShareTea Owner Related URLS
    url(r'^sharetea_owner/sign-in/$', auth_views.login,
    {'template_name': 'sharetea_owner/sign_in.html'},
    name = 'restaurant-sign-in'),
    url(r'^sharetea_owner/sign-out/$', auth_views.logout,
    {'next_page': 'restaurant-sign-in'},
    name = 'restaurant-sign-out'),
    url(r'^api/', include('OnlineOrderApp.urls')),
    url(r'^sharetea_owner/$', views.owner_home,name='owner-home'),
    url(r'^sharetea_owner/sign-up', views.owner_sign_up,name='owner-sign-up'),

    url(r'^sharetea_owner/account/$', views.owner_account,name='owner-acct'),
    url(r'^sharetea_owner/drink/$', views.owner_drink,name='owner-drink'),
    url(r'^sharetea_owner/drink/add/$', views.owner_add_drink,name='owner-add-drink'),
    url(r'^sharetea_owner/drink/edit/(?P<drink_id>\d+)/$', views.owner_edit_drink, name = 'owner-edit-drink'),
    url(r'^sharetea_owner/order/$', views.owner_order,name='owner-order'),
    url(r'^sharetea_owner/report/$', views.owner_report,name='owner-report'),
    url(r'^sharetea_owner/ingredient/$', views.owner_ingredient,name='owner-ingredient'),
    url(r'^sharetea_owner/ingredient/add/$', views.owner_add_ingredient,name='owner-add-ingredient'),
    url(r'^sharetea_owner/ingredient/edit/(?P<ingredient_id>\d+)/$', views.owner_edit_ingredient, name = 'owner-edit-ingredient'),


    # User_Client iOS App related URLS
    url(r'^api/social/', include('rest_framework_social_oauth2.urls')),
    url(r'^api/sharetea_owner/order/notification/(?P<last_request_time>.+)/$', apis.owner_order_notification),
    url(r'^api/sharetea_owner/owners/all/$', apis.get_all_owners, name = 'get-all-owners'),
    url(r'^api/sharetea_owner/owner/(?P<owner_id>\d+)/$', apis.get_owner_by_id, name = 'owner-get-by-id'),
    url(r'^api/sharetea_owner/orders/all/$', apis.get_all_orders, name = 'get-all-orders'),
    url(r'^api/sharetea_owner/order/(?P<order_id>\d+)/$', apis.get_order_by_id, name = 'get-order-by-id'),
    url(r'^api/sharetea_owner/ready_orders/all/$', apis.get_all_ready_orders, name = 'get-all-ready-orders'),


    # API for Customer
    url(r'^api/customer/owners/all/$', apis.get_all_owners, name = 'customer-get-all-owners'),
    # url(r'^api/customer/drinks/all/$', apis.get_all_products, name = 'customer-get-all-products'),
    #url(r'^api/customer/drinks/all/(?P<owner_id>\d+)/$', apis.customer_get_drinks, name = 'customer-get-drinks'),
    # url(r'^api/customer/drinks/all/$', apis.customer_get_drinks, name = 'customer-get-drinks'),
    url(r'^api/customer/order/add/$', apis.customer_add_order, name = 'customer-add-order'),
    url(r'^api/customer/order/latest/$', apis.customer_get_latest_order, name = 'customer-get-latest-order'),
    url(r'^api/customer/access_token/(?P<customer_id>\d+)/$', apis.customer_get_access_token, name = 'customer-get-access-token'),
    url(r'^api/get_auth_token/$', rest_framework_views.obtain_auth_token, name='get_auth_token'),
    url(r'^api/customer/drinks/all/$', apis.customer_get_drinks_by_category, name = 'customer-get-drinks-by-category'),
    url(r'^api/customer/ingredients/all/$', apis.customer_get_topping, name='customer-get-ingredients'),
    url(r'^api/customer/categories/all/$', apis.customer_get_categories, name = 'customer-get-categories'),
    url(r'^api/customer/drinks/total/$', apis.customer_get_total_drinks, name = 'customer-get-total-drinks'),
    url(r'^api/customer/drinks/favorites/$', apis.customer_get_favorite_drinks, name = 'customer-get-favorite-drinks'),

    # APIs for DRIVERS
    url(r'^api/driver/orders/ready/$', apis.driver_get_ready_orders),
    url(r'^api/driver/order/pick/$', apis.driver_pick_order),
    url(r'^api/driver/order/latest/$', apis.driver_get_latest_order),
    url(r'^api/driver/order/complete/$', apis.driver_complete_order),
    url(r'^api/driver/revenue/$', apis.driver_get_revenue),
    url(r'^__debug__/', include(debug_toolbar.urls)),

    url(r'^api/cart/add/$', apis.add_to_cart),
    url(r'^api/cart/remove/$', apis.remove_from_cart),
    url(r'^api/cart/$', apis.get_cart),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OnlineOrderApp/models.py
from __future__ import unicode_literals

# Django Project Imports
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Project Specific Imports
from  OnlineOrderApp.helpermethods import *
from OnlineOrderApp.Helpers import *

from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings

# This code is triggered whenever a new user has been created and saved to the database

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)



# Create your models here.
class Owner(models.Model):
    """Class of ShareTea Owners"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='owner')
    name = models.CharField(max_length=500)
    phone = models.CharField(max_length=500)
    address = models.CharField(max_length=500)
    zipcode = models.IntegerField(default=98004)
    logo = models.ImageField(upload_to='owner_logo/', blank=False)

    def __str__(self):
        return self.user.username
    """Get User Name"""
    def getName(self):
        return self.name
    """Get User Phone"""
    def getPhone(self):
        return self.phone
    """Get User Instance"""
    def getUser(self):
        return self.user
    """Get User Address"""
    def getAddress(self):
        return self.address


class Customer(models.Model):
    """Class for ShareTea customers"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500)
    address = models.CharField(max_length=500)

    def __str__(self):
        return self.user.username

    """Get User Name"""
    def getEmail(self):
        return self.user.email

    """Get User Name"""
    def getName(self):
        return self.user.get_full_name()
    """Get User Phone"""
    def getPhone(self):
        return self.phone
    """Get User Instance"""
    def getUser(self):
        return self.user
    """Get User Address"""
    def getAddress(self):
        return self.address
    """Get User Avatar"""
    def getAvatar(self):
        return self.avatar


class Driver(models.Model):
    """Class for ShareTea Drivers"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='driver')
    avatar = models.CharField(max_length=500)
    phone = models.CharField(max_length=500)
    address = models.CharField(max_length=500)

    def __str__(self):
        return self.user.get_full_name()


class Category(models.Model):
    name = models.CharField(max_length=500, default='MilkTea')
    # owner = models.ForeignKey(Owner, related_name='owner')
    calories = models.IntegerField(max_length=500, default=0)
    short_description = models.CharField(max_length=500, default='Tea')
    image = models.ImageField(upload_to='category_images/', blank=True, null=True, default = '')
    def __str__(self):
        return self.name


class Drink(models.Model):
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE, related_name='category_owner')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    name = models.CharField(max_length=500)
    # category = models.CharField(max_length=500 , default='MilkTea')
    short_description = models.CharField(max_length=500)
    image = models.ImageField(upload_to='drink_images/', blank=False)
    price = models.FloatField(default=3.75)
    calories = models.IntegerField(max_length=500, default=0)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name

# class Favorites(models.Model):


class Ingredient(models.Model):
#    drink = models.ForeignKey(Drink, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=500, default='BlackBoba')
    short_description = models.CharField(max_length=500)
    ingredient_type = models.CharField(max_length=1,default='I')
    image = models.ImageField(upload_to='ingredient_images/', blank=False)
    price = models.FloatField(default=0.50)
    calories = models.IntegerField(max_length=500, default=0)
    available = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Order(models.Model):
    RECEIVED = 1
    PROCESSING = 2
    MAKING = 3
    READY = 4
    ONTHEWAY = 5
    DELIVERED = 6

    STATUS_CHOICES = (
        (RECEIVED, "Received"),
        (PROCESSING, "Processing"),
        (MAKING, "Making"),
        (READY, "Ready"),
        (ONTHEWAY, "OnTheWay"),
        (DELIVERED, "Delivered"),
    )

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    owner = models.ForeignKey(Owner, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=500)
    total = models.FloatField(default=0.000000)
    status = models.IntegerField(choices = STATUS_CHOICES)
    created_at = models.DateTimeField(default = timezone.now)
    picked_At = models.DateTimeField(blank = True, null = True)
    quantity = models.IntegerField(default=0)

    def __str__(self):
        return str(self.id)


class OrderDetails(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_details')
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE)
    ingredients = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='ingredients', default=1)
    quantity = models.IntegerField()
    sub_total = models.FloatField(default=0.000000)
    ingredient = models.ManyToManyField(Ingredient)

    def __str__(self):
        return str(self.id)


from decimal import Decimal


class DrinkRecord(models.Model):
    """
    A record of a how popular a product is.
    This used be auto-merchandising to display the most popular
    products.
    """

    drink = models.OneToOneField(
        'OnlineOrderApp.Drink', verbose_name=("Drink"),
        related_name='stats', on_delete=models.CASCADE)

    # Data used for generating a score
    num_views = models.PositiveIntegerField(('Views'), default=0)
    num_cart_additions = models.PositiveIntegerField(
        ('Cart Additions'), default=0)
    num_purchases = models.PositiveIntegerField(
        ('Purchases'), default=0, db_index=True)

    # Product score - used within search
    score = models.FloatField(('Score'), default=0.00)

    # class Meta:
    #     abstract = True
    #     app_label = 'OnlineOrderApp'
    #     ordering = ['-num_purchases']
    #     verbose_name = _('Drink record')
    #     verbose_name_plural = _('Drink records')

    def __str__(self):
        return _("Record for '%s'") % self.product

class DrinksRecordForUser(models.Model):
    """
    A record of a user's drink record.
    """
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, default=0)
    drink = models.ForeignKey(Drink, on_delete=models.CASCADE, default=0)
    num_orders = models.PositiveIntegerField(
        ('Orders'), default=0, db_index=True)
    def __str__(self):
        return str(self.id)


class UserRecord(models.Model):
    """
    A record of a user's activity.
    """

    # user = models.OneToOneField(User, verbose_name=("User"),
    #                             on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, default=0, db_index=True)

    # Order stats
    num_orders = models.PositiveIntegerField(
        ('Orders'), default=0, db_index=True)
    total_spent = models.DecimalField(('Total Spent'), decimal_places=2,
                                      max_digits=12, default=Decimal('0.00'))
    date_last_order = models.DateTimeField(
        ('Last Order Date'), blank=True, null=True)

    drink = models.ForeignKey(Drink, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.customer.user.username

OnlineOrderApp/forms.py
from django import forms

from django.contrib.auth.models import User
from OnlineOrderApp.models import Owner, Drink, Ingredient

class UserForm(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "password", "first_name", "last_name", "email")


class UserFormEdit(forms.ModelForm):
    email = forms.CharField(max_length=100, required=True)
    #password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("first_name", "last_name", "email")

# class RestaurantForm(forms.ModelForm):
class OwnerForm(forms.ModelForm):
    class Meta:
        model = Owner
        fields = ("name", "phone", "address", "zipcode", "logo")

class DrinkForm(forms.ModelForm):
    class Meta:
        model = Drink
        exclude = ("owner",)

class IngredientForm(forms.ModelForm):
    class Meta:
        model = Ingredient
        exclude = ("drink",)

OnlineOrderApp/templates/sharetea_owner/account.html
{% extends 'sharetea_owner/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class="col-lg-offset-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Account
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form user_form %}
                    {% bootstrap_form owner_form %}
                    <button type="submit" class="btn btn-pink">Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

OnlineOrderApp/templates/sharetea_owner/add_drink.html
{% extends 'sharetea_owner/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class="col-lg-offset-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Add Drink
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-pink">Create</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

OnlineOrderApp/templates/sharetea_owner/add_ingredient.html
{% extends 'sharetea_owner/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class="col-lg-offset-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Add Ingredient
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-pink">Create</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

OnlineOrderApp/templates/sharetea_owner/base.html
{% extends 'base.html' %}

{% block title %} ShareTea {% endblock %}

{% block script %}
    <script>
        $(document).ready(function() {
            var now = new Date();
            setInterval(function() {
                $.ajax({
                    url: '/api/sharetea_owner/order/notification/' + now.toISOString() + '/',
                    method: 'GET',
                    success: function(data) {
                        if (data['notification'] === 0) {
                            $('.badge').text('');
                        } else {
                            $('.badge').text(data['notification']);
                        }
                    }
                })
            }, 3000)
        })

    </script>
{% endblock %}

{% block sidebar %}

  {% url 'owner-order' as owner_order_url %}
  {% url 'owner-drink' as owner_drink_url %}
  {% url 'owner-report' as owner_report_url %}
  {% url 'owner-account' as owner_account_url %}
  {% url 'owner-ingredient' as owner_ingredient_url %}

  <div class="text-center">
    <img class="img-circle" src="{{MEDIA_URL}}{{request.user.owner.logo}}"
      width="70" height="70">
      <br/>
      <br/>
      <h4>Hi, {{ request.user.get_full_name }}</h4>
      <h5>{{ request.user.owner.name }}</h5>
  </div>

  <div class="list-group">
    <span class="text-uppercase">Dashboard</span>

    <a href="{% url 'owner-order' %}"
        class="list-group-item {% if request.path == owner_order_url %} active {% endif %} ">
        Orders
        <span class="badge"></span>
    </a>
    <a href="{% url 'owner-drink' %}"
        class="list-group-item {% if request.path == owner_drink_url %} active {% endif %} ">Drinks</a>

    <a href="{% url 'owner-ingredient' %}"
        class="list-group-item {% if request.path == owner_ingredient_url %} active {% endif %} ">Ingredients</a>
    <a href="{% url 'owner-report' %}"
        class="list-group-item {% if request.path == owner_report_url %} active {% endif %} ">Reports</a>

    <span class="text-uppercase">Profile</span>
    <a href="{% url 'owner-acct' %}" class="list-group-item">Account</a>
  </div>

  <div class="text-center">
    <a href="{% url 'restaurant-sign-out' %}?next={{ request.path }}"
        class="btn btn-pink">Logout</a>
  </div>
{% endblock %}

OnlineOrderApp/templates/sharetea_owner/drink.html
{% extends 'sharetea_owner/base.html' %}

{% block page %}

    <div class="panel">
        <div class="panel-heading bg-blue">
            <h4 class="panel-title text-center text-white">Drinks</h4>
        </div>
        <div class="panel-body">
            <div class="text-right">
                <a href="{% url 'owner-add-drink' %}" class="btn btn-pink">Add Drink</a>
                <br/>
                <br/>
            </div>

            <table class="table table-hover table-striped">
                <thead>
                  <tr class="bg-gray text-white">
                    <th>Id</th>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Short Description</th>
                    <th>Price</th>
                    <th>Calories</th>
                    <th class="text-center">Image</th>
                  </tr>
                </thead>
                <tbody>
                    {% for drink in drinks %}
                        <tr>
                          <td scope="row">{{ drink.id }}</td>
                          <td><a href="{% url 'owner-edit-drink' drink.id %}">{{ drink.name }}</a></td>
                          <td>{{ drink.category }}</td>
                          <td>{{ drink.short_description }}</td>
                          <td>{{ drink.price }}</td>
                          <td>{{ drink.calories}}</td>
                          <td class="text-center"><img class="img-rounded"
                              src="{{ MEDIA_URL }}{{ drink.image }}" width="50" height="50"></td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>



{% endblock %}

OnlineOrderApp/templates/sharetea_owner/edit_drink.html
{% extends 'sharetea_owner/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class="col-lg-offset-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Edit Drink
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-pink">Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

OnlineOrderApp/templates/sharetea_owner/edit_ingredient.html
{% extends 'sharetea_owner/base.html' %}
{% load bootstrap3 %}

{% block page %}
    <div class="col-lg-offset-2 col-lg-8">
        <div class="panel">
            <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Edit Ingredient
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <button type="submit" class="btn btn-pink">Update</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

OnlineOrderApp/templates/sharetea_owner/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="=utf-8">
  <title>Home Page</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
  ShareTeaHomeOwner Page
  <a href="{% url 'restaurant-sign-out' %}">Log Out</a>
</body>
</html>

OnlineOrderApp/templates/sharetea_owner/ingredient.html
{% extends 'sharetea_owner/base.html' %}

{% block page %}

    <div class="panel">
        <div class="panel-heading bg-blue">
            <h4 class="panel-title text-center text-white">Ingredients</h4>
        </div>
        <div class="panel-body">
            <div class="text-right">
                <a href="{% url 'owner-add-ingredient' %}" class="btn btn-pink">Add Ingredient</a>
                <br/>
                <br/>
            </div>

            <table class="table table-hover table-striped">
                <thead>
                  <tr class="bg-gray text-white">
                    <th>Id</th>
                    <th>Name</th>
                    <th>Short Description</th>
                    <th>Price</th>
                    <th>Calories</th>
                    <th>Available</th>
                    <th class="text-center">Image</th>
                  </tr>
                </thead>
                <tbody>
                    {% for ingredient in ingredients %}
                        <tr>
                          <td scope="row">{{ ingredient.id }}</td>
                          <td><a href="{% url 'owner-edit-ingredient' ingredient.id %}">{{ ingredient.name }}</a></td>
                          <td>{{ ingredient.short_description }}</td>
                          <td>{{ ingredient.price }}</td>
                          <td>{{ ingredient.calories}}</td>
                          <td>{{ ingredient.available}}</td>
                          <td class="text-center"><img class="img-rounded"
                              src="{{ MEDIA_URL }}{{ ingredient.image }}" width="50" height="50"></td>
                        </tr>

                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>



{% endblock %}

OnlineOrderApp/templates/sharetea_owner/order.html
{% extends 'sharetea_owner/base.html' %}

{% block page %}

    <div class="panel">
        <div class="panel-heading bg-blue">
            <h4 class="panel-title text-center text-white">Orders</h4>
        </div>
        <div class="panel-body">
            <br/>
            <table class="table table-hover table-striped">
                <thead>
                  <tr class="bg-gray text-white">
                    <th>Id</th>
                    <th>Order Details</th>
                    <th>Customer</th>
                    <th>Driver</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr class="active">
                        <td scope="row">{{ order.id }}</td>
                        <td>
                          {% for od in order.order_details.all %}
                              {{ od.drink.name }} {{ od.drink.price }}
                              x {{ od.quantity }} = ${{ od.sub_total }}
                          {% endfor %}
                        </td>
                        <td>{{ order.customer }}</td>
                        <td>{{ order.driver }}</td>
                        <td>{{ order.total }}</td>
                        <td>{{ order.get_status_display }}</td>
                        <td>
                            {% if order.status == 3 %}
                                <form method="POST">
                                  {% csrf_token %}
                                  <input name="id" value="{{ order.id }}" hidden>
                                  <button class="btn btn-success">Ready</button>
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

OnlineOrderApp/templates/sharetea_owner/report.html
{% extends 'sharetea_owner/base.html' %}

{% block script %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.2.2/Chart.min.js"></script>
{% endblock %}

{% block page %}

    <div class="row">
        <div class="col-lg-8">

            <!-- Revenue by Week -->
            <div class="panel">
                <div class="panel-heading bg-blue">
                  <h4 class="panel-title text-center text-white">
                      Revenue by Week
                  </h4>
                </div>
                <div class="panel-body">
                    <canvas id="revenueChart" height="110"></canvas>
                    <script>
                        var ctx = document.getElementById("revenueChart").getContext("2d");
                        var data = {
                            labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
                            datasets: [
                                {
                                    label: "Revenue by Week",
                                    backgroundColor: "rgba(54,162,235,0.9)",
                                    hoverBackgroundColor: "rgba(54,162,235,1)",
                                    data: {{ revenue }}
                                }
                            ]
                        };

                        new Chart(ctx, {
                          type: 'bar',
                          data: data
                        });

                    </script>
                </div>
            </div>

            <!-- Orders by Week -->
            <div class="panel">
                <div class="panel-heading bg-blue">
                  <h4 class="panel-title text-center text-white">
                      Order by Week
                  </h4>
                </div>
                <div class="panel-body">
                    <canvas id="orderChart" height="110"></canvas>
                    <script>
                        var ctx = document.getElementById("orderChart").getContext("2d");
                        var data = {
                            labels: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
                            datasets: [
                                {
                                    label: "Order by Week",
                                    backgroundColor: "rgba(255,99,132,0.9)",
                                    hoverBackgroundColor: "rgba(255,99,132,1)",
                                    data: {{ orders }}
                                }
                            ]
                        };

                        new Chart(ctx, {
                          type: 'bar',
                          data: data
                        });

                    </script>
                </div>
            </div>


        </div>
        <div class="col-lg-4">

          <!-- TOP 3 Drinks -->
          <div class="panel">
              <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Top 3 Drinks
                </h4>
              </div>
              <div class="panel-body">
                  <canvas id="drinkChart" height="242"></canvas>
                  <script>
                      var ctx = document.getElementById("drinkChart").getContext("2d");
                      var data = {
                          labels: {{ drink.labels|safe }},
                          datasets: [
                              {
                                  backgroundColor: [
                                    "#36A2EB", "#FFCE56", "#FF6384"
                                  ],
                                  data: {{ drink.data }}
                              }
                          ]
                      };

                      new Chart(ctx, {
                        type: 'pie',
                        data: data
                      });

                  </script>
              </div>
          </div>

          <!-- TOP 3 Driver ALL TIME -->
          <div class="panel">
              <div class="panel-heading bg-blue">
                <h4 class="panel-title text-center text-white">
                    Top 3 Drivers
                </h4>
              </div>
              <div class="panel-body">
                  <canvas id="driverChart" height="242"></canvas>
                  <script>
                      var ctx = document.getElementById("driverChart").getContext("2d");
                      var data = {
                          labels: {{ driver.labels|safe }},
                          datasets: [
                              {
                                  backgroundColor: [
                                    "#36A2EB", "#FFCE56", "#FF6384"
                                  ],
                                  data: {{ driver.data }}
                              }
                          ]
                      };

                      new Chart(ctx, {
                        type: 'pie',
                        data: data
                      });

                  </script>
              </div>
          </div>
        </div>
    </div>
{% endblock %}